networks:
  imaginary:
    driver: overlay
    attachable: true

services:
  imaginary:
    networks:
      - imaginary
    image: nextcloud/aio-imaginary:latest
    hostname: imaginary
    restart: unless-stopped
    environment:
      PORT: 9000
      TZ: 'Europe/Berlin'
    # command: ["-concurrency", "10", "-enable-url-source"]
    cap_add:
      - CAP_SYS_NICE
    deploy:
      # mode: global
      replicas: 6
      endpoint_mode: vip
      # endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role==worker"
          # - "node.hostname==THEHOSTNAME"
