#!/usr/bin/env bash

export RESTIC_PASSWORD="$NEXTCLOUD_RESTIC_PASSWORD"
export RESTIC_REPOSITORY="$NEXTCLOUD_RESTIC_REPO_LOCAL"
restic init
export RESTIC_REPOSITORY="$NEXTCLOUD_RESTIC_REPO_AZURE"
restic init
